# Use Ubuntu as the image we add the g++ compiler to and do the compile/test cycle within
FROM ubuntu:18.10

# install g++ 8 and python 3 (this part takes a while first time)
RUN apt-get update && apt-get install -y g++-8 python3 openjdk-8-jdk

